import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers/Providers";
import { Footer } from "@/components/footer/Footer";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Watchly.IO",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
      <body className={poppins.className + " min-h-screen flex flex-col justify-between"}>
        <Providers>
          {children}
          <div className="mt-10">
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
    </SessionProvider>
    
  );
}
